/// Message types — the normalized conversation layer.
///
/// All provider-specific message formats are normalized to these types
/// at the trait boundary. Providers are responsible for translating
/// to/from their native format internally.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// The role of a participant in a conversation.
///
/// Normalized across all LLM providers. Provider-specific roles
/// (e.g., Anthropic's `tool` result format) are mapped to these variants.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum MessageRole {
    /// The system prompt establishing context and instructions.
    System,
    /// A message from the human user.
    User,
    /// A response generated by the LLM assistant.
    Assistant,
    /// A tool call result message returned to the LLM.
    Tool,
}

/// A single message in a conversation.
///
/// Used both in the `CompletionRequest` sent to providers and in the
/// persisted `ConversationHistory` stored in session state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentMessage {
    /// Unique ID for this message (for deduplication and indexing).
    pub id: Uuid,
    /// The role of the message author.
    pub role: MessageRole,
    /// The text or structured content of the message.
    pub content: MessageContent,
    /// When this message was created.
    pub created_at: DateTime<Utc>,
    /// For tool messages: the call ID this result corresponds to.
    pub tool_call_id: Option<String>,
    /// For assistant messages with tool calls: the tool calls requested.
    pub tool_calls: Vec<ToolCallInMessage>,
    /// Token count estimate for this message (populated after LLM call).
    pub token_count: Option<usize>,
}

/// The content of a message — text or structured blocks.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContent {
    /// Plain text content.
    Text(String),
    /// Structured multi-part content (text + images + tool results).
    Blocks(Vec<ContentBlock>),
}

/// A single content block within a multi-part message.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentBlock {
    /// Plain text block.
    Text { text: String },
    /// Base64-encoded image block (requires vision capability).
    Image {
        mime_type: String,
        data: String,
    },
    /// A tool use request emitted by the assistant.
    ToolUse {
        id: String,
        name: String,
        input: serde_json::Value,
    },
    /// A tool result returned to the LLM.
    ToolResult {
        tool_use_id: String,
        content: Vec<ContentBlock>,
        is_error: bool,
    },
    /// An extended thinking/reasoning block (Anthropic, o-series).
    Thinking {
        thinking: String,
        signature: Option<String>,
    },
}

/// A tool call embedded in an assistant message.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallInMessage {
    /// Provider-assigned call identifier for correlating results.
    pub call_id: String,
    /// The name of the tool being called.
    pub tool_name: String,
    /// The arguments the model passed to the tool.
    pub arguments: serde_json::Value,
}

/// A single turn in the conversation — a paired (user message, assistant response).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConversationTurn {
    /// Sequential turn index (0-based).
    pub index: usize,
    /// The user's input message.
    pub user_message: AgentMessage,
    /// The assistant's response.
    pub assistant_message: AgentMessage,
    /// Total tokens consumed in this turn (input + output).
    pub total_tokens: usize,
    /// Wall-clock duration of the LLM call in milliseconds.
    pub latency_ms: u64,
    /// The provider and model used for this turn.
    pub provider: String,
    /// The model used for this turn.
    pub model: String,
}

/// The complete conversation history for a session.
///
/// Stored in session state and used to reconstruct the conversation
/// for subsequent LLM calls, context budget tracking, and replay.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ConversationHistory {
    /// Ordered list of all messages in the session.
    pub messages: Vec<AgentMessage>,
    /// Total token count of all messages (running total).
    pub total_tokens: usize,
    /// Whether the history has been compacted (older messages summarized).
    pub is_compacted: bool,
    /// If compacted, the summary that replaced earlier messages.
    pub compaction_summary: Option<String>,
}

impl ConversationHistory {
    /// Creates a new empty conversation history.
    pub fn new() -> Self {
        Self::default()
    }

    /// Appends a message to the history and updates the running token count.
    pub fn push(&mut self, message: AgentMessage) {
        if let Some(count) = message.token_count {
            self.total_tokens += count;
        }
        self.messages.push(message);
    }

    /// Returns the most recent N messages (useful for context window trimming).
    pub fn last_n(&self, n: usize) -> &[AgentMessage] {
        let start = self.messages.len().saturating_sub(n);
        &self.messages[start..]
    }

    /// Returns the message count.
    pub fn len(&self) -> usize {
        self.messages.len()
    }

    /// Returns true if the history contains no messages.
    pub fn is_empty(&self) -> bool {
        self.messages.is_empty()
    }
}
